# Qualitative Asessment of Neurotransmitters
This journal will import, calculate and plot the qualitative values for the neurotransmitters assayed during microdialysis

In [7]:
# This cell imports necessary libraries and provides their respective alias

import pandas as pd # used to manipulate CSVs
import numpy as np # used to perform calculations
from scipy.stats import linregress as linreg # used to extract m, b, & r^2
import matplotlib.pyplot as plt # used to generate plots

In [8]:
#This cell will import the csv files containing, respectively, data from:

Tissues = pd.read_csv('qualitative.csv') # the microdissected samples
Curves = pd.read_csv('microdialisis_curves.csv') # standard curves for given HPLC Runs 

print("Standard Curve Values:")
display(Curves)

print("\nExperimental Values:")
display(Tissues)

Standard Curve Values:

,standard curve,Dopa Stock (V.s),5-HT Stock (V.s),Curve,Dopa Stock (pmol),5-Ht Stock (pmol)
0,day 1 D2&D3,1.28,2.02,0,32.64130,28.37440
1,day 1 D2&D3,0.63,0.96,0,16.32070,14.18720
2,day 1 D2&D3,0.12,0.19,0,1.63207,1.41872
3,day 1 D2&D3,0.06,0.10,0,0.16321,0.14187
4,day 1 D2&D3,0.01,0.02,0,0.08160,0.07094
5,day 2 D2&D3,0.01,0.02,1,0.08160,0.07094
6,day 2 D2&D3,0.06,0.09,1,0.16321,0.14187
7,day 2 D2&D3,0.12,0.19,1,1.63207,1.41872
8,day 2 D2&D3,0.62,0.98,1,16.32070,14.18720
9,day 2 D2&D3,1.21,1.93,1,32.64130,28.37440
10,day 1 D5,0.01,0.02,2,0.08160,0.07094
11,day 1 D5,0.07,0.10,2,0.16321,0.14187
12,day 1 D5,0.13,0.20,2,1.63207,1.41872
13,day 1 D5,0.65,1.02,2,16.32070,14.18720
14,day 2 D5,0.01,0.02,3,0.08160,0.07094
15,day 2 D5,0.05,0.10,3,0.16321,0.14187
16,day 2 D5,0.12,0.21,3,1.63207,1.41872
17,day 2 D5,0.57,0.99,3,16.32070,14.18720
18,day 2 D4,0.01,0.02,4,0.08160,0.07094
19,day 2 D4,0.06,0.11,4,0.16321,0.14187
20,day 2 D4,0.12,0.22,4,1.63207,1.41872
21,day 2 D4,0.59,1.08,4,16.32070,14.18720

Experimental Values:

   Animal  Experiment Dopa (V.s) 5-HT (V.s)  time  Standard Curve  Unnamed: 6
0      D2         1.0          Q       0.01     5               0         NaN
1      D2         1.0          0          Q    10               0         NaN
2      D2         1.0          0          Q    15               0         NaN
3      D2         1.0          0          Q    20               0         NaN
4      D2         1.0          0        0.1    25               0         NaN
5      D2         1.0          0        0.1    30               0         NaN
6      D2         1.0          0          Q    35               0         NaN
7      D2         1.0          0          Q    40               0         NaN
8      D2         1.0          0          Q    45               0         NaN
9      D2         1.0          0          Q    50               0         NaN
10     D2         1.0          0          Q    55               0         NaN
11     D2         1.0          0          Q    60               0         NaN
12     D2         2.0          Q          Q     5               1         NaN
13     D2         2.0          0          Q    10               1         NaN
14     D2         2.0          0          Q    15               1         NaN
15     D2         2.0          Q          Q    20               1         NaN
16     D2         2.0          Q          Q    25               1         NaN
17     D2         2.0          Q          Q    30               1         NaN
18     D2         2.0          0          Q    35               1         NaN
19     D2         2.0          0          0    40               1         NaN
20     D2         2.0          0          Q    45               1         NaN
21     D2         2.0          0          Q    50               1         NaN
22     D2         2.0          0          Q    55               1         NaN
23     D2         2.0          Q        0.1    60               1         NaN
24     D2         2.0          Q        0.4    65               1         NaN
25     D2         2.0          0        0.2    70               1         NaN
26     D2         2.0          0        0.1    75               1         NaN
27     D2         2.0          0        0.1    80               1         NaN
28     D2         2.0          0          Q    85               1         NaN
29     D2         2.0          0          Q    90               1         NaN
..    ...         ...        ...        ...   ...             ...         ...
58     D3         2.0          0          Q    90               1         NaN
59     D5         1.0       0.02       0.03     5               2         NaN
60     D5         1.0          Q          Q    10               2         NaN
61     D5         1.0          Q          Q    15               2         NaN
62     D5         1.0          Q          Q    20               2         NaN
63     D5         1.0          Q          0    25               2         NaN
64     D5         1.0          Q          0    30               2         NaN
65     D5         1.0          Q          0    35               2         NaN
66     D5         1.0          Q          0    40               2         NaN
67     D5         1.0          Q          0    45               2         NaN
68     D5         1.0          Q          0    50               2         NaN
69     D5         1.0          Q          0    55               2         NaN
70     D5         2.0       0.01       0.04     5               3         NaN
71     D5         2.0       0.02       0.03    10               3         NaN
72     D5         2.0          Q       0.01    15               3         NaN
73     D5         2.0          Q          Q    20               3         NaN
74     D5         2.0          Q          Q    25               3         NaN
75     D5         2.0          0          0    30               3         NaN
76     D5         2.0          0          0    35               3         NaN
77     D4         2.0          Q          Q     5               3         NaN
78     D4         NaN          Q          Q    10               4         NaN
79     D4         NaN          Q          Q    15               4         NaN
80     D4         NaN          Q          Q    20               4         NaN
81     D4         NaN          Q          0    25               4         NaN
82     D4         NaN          Q          0    30               4         NaN
83     D4         NaN          Q          0    35               4         NaN
84     D4         NaN          Q          0    40               4         NaN
85     D4         NaN          Q          0    45               4         NaN
86     D4         NaN          0          0    50               4         NaN
87     D4         NaN          0          0    55               4         NaN

[88 rows x 7 columns]

In [ ]:
for ii in range(len(Tissues)):
    if Tissues.loc[ii,"Animal"]=="D2" and Tissues.loc[ii, "Experiment"]==1:
        Tissues.loc[ii,"Standard Curve"]=0

In [29]:
ii=4
Curves['5-HT Stock (V.s)'][Curves['Curve']==ii]

18    0.02
19    0.11
20    0.22
21    1.08
Name: 5-HT Stock (V.s), dtype: float64

In [27]:


#This cell will create an array containing the coefficients
lin = pd.DataFrame({'m': [], 'b': [], 'r2': []}) #Create dataframe
Dopa = lin
Ser = lin

# This for loop will iterate through all unique HPLC runs to calculate and store m, b, and r^2
for ii in range(max(Curves['Curve'])): #uses max to find last experiment
    #calculates values for dopamine
    lr = linreg(Curves['Dopa Stock (V.s)'][Curves['Curve']==ii], Curves['Dopa Stock (pmol)'][Curves['Curve']==ii])
    m=lr[0]
    b=lr[1]
    r2=lr[2]

    #stores values for dopamine
    Dopa= Dopa.append({'m': m, 'b': b, 'r2': r2}, ignore_index=True)
    
    #calculates values for serotonin
    lr = linreg(Curves['5-HT Stock (V.s)'][Curves['Curve']==ii], Curves['5-Ht Stock (pmol)'][Curves['Curve']==ii])
    m=lr[0]
    b=lr[1]
    r2=lr[2]

    #stores values for serotonin
    Ser= Ser.append({'m': m, 'b': b, 'r2': r2}, ignore_index=True)
    print(ii)
print("Dopamine Regression Values:")
display(Dopa)
print("\nSerotonin Regression Values:")
display(Ser)

0
1
2
3
Dopamine Regression Values:

           m         b        r2
0  26.393232 -0.917382  0.999022
1  27.874154 -1.093382  0.999157
2  26.668151 -1.184257  0.995372
3  30.284823 -1.129009  0.995505

Serotonin Regression Values:

           m         b        r2
0  14.613994 -0.777382  0.998420
1  15.202917 -0.921647  0.999260
2  14.754665 -0.988130  0.996389
3  15.256568 -1.079985  0.995259

In [18]:
ii =78
#Tissues['Standard Curve'][ii]
#(0.08160 -Dopa['b'][(Tissues['Standard Curve'][ii])])/Dopa['m'][(Tissues['Standard Curve'][ii])]
Dopa['m'][(Tissues['Standard Curve'][ii])]

KeyError: 4

In [10]:
# This cell will calculate the concentration of Dopa and 5-HT in pmol

# Creates empty columns in dataframe Tissues
Tissues['Dopa (pmol)']=np.nan
Tissues['5-HT (pmol)']=np.nan
Tissues['Dopa (pM/mg)']=np.nan
Tissues['5-HT (pM/mg)']=np.nan

# This for loop will iterate through all tissue samples and save the pmol concentration of each
for ii in range(len(Tissues)) :
    print(ii)
    if (Tissues['Dopa (V.s)'][ii] != 'Q'):
# x=(y-b)/m for Dopamine
        Tissues.loc[ii, 'Dopa (pmol)'] = (float(Tissues['Dopa (V.s)'][ii]) -Dopa['b'][(Tissues['Standard Curve'][ii])])/Dopa['m'][(Tissues['Standard Curve'][ii])]
# Removes Negatives  
        if Tissues['Dopa (pmol)'][ii] < 0:
            Tissues.loc[ii,'Dopa (pmol)'] = 0
#  Sets concentration to maximum possible from experimental standard curve 
    else :
        Tissues.loc[ii,'Dopa (pmol)'] = (0.08160 -Dopa['b'][(Tissues['Standard Curve'][ii])])/Dopa['m'][(Tissues['Standard Curve'][ii])]
    
    Tissues.loc[ii,'Dopa (pM/mg)'] = (Tissues['Dopa (pmol)'][ii])
            
    if (Tissues['5-HT (V.s)'][ii] != 'Q'):
# x=(y-b)/m for 5-HT
        Tissues.loc[ii,'5-HT (pmol)'] = (float(Tissues['5-HT (V.s)'][ii])-Ser['b'][(Tissues['Standard Curve'][ii])])/Ser['m'][(Tissues['Standard Curve'][ii])]
# Removes Negatives
        if float(Tissues['5-HT (pmol)'][ii]) < 0:
            Tissues.loc[ii,'5-HT (pmol)'] = 0   
#  Sets concentration to maximum possible from experimental standard curve for readings that are over
    else :
        Tissues.loc[ii,'5-HT (pmol)'] = (0.07094 -Ser['b'][(Tissues['Standard Curve'][ii])])/Ser['m'][(Tissues['Standard Curve'][ii])]
# Converts 
    Tissues.loc[ii,'5-HT (pM/mg)'] = (Tissues['5-HT (pmol)'][ii])
    
    
    #except KeyError:
            #print('error')
display(Tissues[['Condition','Animal','Tissue','Dopa (pmol)','Dopa (pM/mg)','5-HT (pmol)','5-HT (pM/mg)']])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78

KeyError: 4

In [ ]:
# This cell will calculated average concentrations and RMD

# Create data frame for output and its index, respectively
Agg =pd.DataFrame()
kk=0

# Iteratively finds each combination of Condition and Tissue to extract aggregated data from
for jj in range(len(pd.unique(Tissues['Condition']))): #Iterate through Conditions
    for ii in range(len(pd.unique(Tissues['Tissue']))): #Iterate through Tissues

# Calculates and populates data for each aggregate value
        Agg.loc[kk,'Condition'] = pd.unique(Tissues['Condition'])[jj]
        Agg.loc[kk,'Tissue'] = pd.unique(Tissues['Tissue'])[ii]
        Agg.loc[kk,'Dopa (pM/mg)'] = (np.average(Tissues.loc[(Tissues['Condition']==pd.unique(Tissues['Condition'])[jj]) & 
                               (Tissues['Tissue']==pd.unique(Tissues['Tissue'])[ii]), 
                               ['Dopa (pM/mg)']]))
        Agg.loc[kk,'Std Dopa'] = ((np.std(Tissues.loc[(Tissues['Condition']==pd.unique(Tissues['Condition'])[jj]) & 
                               (Tissues['Tissue']==pd.unique(Tissues['Tissue'])[ii]), 
                               ['Dopa (pM/mg)']])))[0]             
        Agg.loc[kk,'RMD Dopa'] = ((np.std(Tissues.loc[(Tissues['Condition']==pd.unique(Tissues['Condition'])[jj]) & 
                               (Tissues['Tissue']==pd.unique(Tissues['Tissue'])[ii]), 
                               ['Dopa (pM/mg)']]))/Agg['Dopa (pM/mg)'][kk])[0]             
        Agg.loc[kk,'5-HT (pM/mg)'] = (np.average(Tissues.loc[(Tissues['Condition']==pd.unique(Tissues['Condition'])[jj]) & 
                               (Tissues['Tissue']==pd.unique(Tissues['Tissue'])[ii]), 
                               ['5-HT (pM/mg)']]))        
        Agg.loc[kk,'RMD 5-HT'] = ((np.std(Tissues.loc[(Tissues['Condition']==pd.unique(Tissues['Condition'])[jj]) & 
                               (Tissues['Tissue']==pd.unique(Tissues['Tissue'])[ii]), 
                               ['5-HT (pM/mg)']]))/Agg['5-HT (pM/mg)'][kk])[0]
        Agg.loc[kk,'Std 5-HT'] = ((np.std(Tissues.loc[(Tissues['Condition']==pd.unique(Tissues['Condition'])[jj]) & 
                               (Tissues['Tissue']==pd.unique(Tissues['Tissue'])[ii]), 
                               ['5-HT (pM/mg)']])))[0]

# Increase index of output for next data extraction
        kk=kk+1
        
display(Agg)

In [ ]:
# This cell will generate a bar graph for Dopamine concentrations from the newly calculated concentrations

#Parameters and for loop to iterate through each condition and determine spacing
fig = plt.figure()
ax = fig.add_subplot(111)

space = 0.4

conditions = pd.unique(Agg['Condition'])

n = len(conditions)

width = (1 - space) / (len(conditions))

for ii,cond in enumerate(conditions):
    vals = Agg['Dopa (pM/mg)'][Agg['Condition']==cond]
    STD = Agg['Std Dopa'][Agg['Condition']==cond]
    col = ['b', 'y']
    pos = [j - (1 - space) / 2. + ii * width for j in range(1,len(source)+1)]
    ax.bar(pos, vals, width=width, 
           color= (col[ii]), edgecolor ='k', linewidth= 1,
           yerr=STD, ecolor ='k', capsize = 3,
           label=cond)

font = {'fontname':'Times New Roman'}    
    
#X-axis parameters
ax.set_xticks([j - (1.3 - space) / 2. + ii * width for j in range(1,len(source)+1)])
ax.set_xticklabels(Agg['Tissue'], **font)
plt.setp(plt.xticks()[1], rotation=0)

#Y-axis parameters
ax.set_ylabel('Dopamine Concentration (pM/mg)', **font)

#Title and legend parameters
ax.set_title("Dopamine Concentration", **font)
handles, labels = ax.get_legend_handles_labels()
ax.legend(handles[::-1], labels[::-1])

# Hide the right and top spines
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)
plt.legend(frameon=False)

display()

plt.savefig('Dopamine_Conc_Microdissection.png', dpi=300, transparent=True)